import { createSlice } from '@reduxjs/toolkit'

const initialState = {
  query: '',
  recentSearches: JSON.parse(localStorage.getItem('devhub-recent-searches')) || [],
  filters: {
    language: '',
    sort: 'stars',
    order: 'desc',
  },
}

const searchSlice = createSlice({
  name: 'search',
  initialState,
  reducers: {
    // Set the current search query
    setQuery: (state, action) => {
      state.query = action.payload
    },
    
    // Add to recent searches (max 10, no duplicates)
    addRecentSearch: (state, action) => {
      const term = action.payload.trim()
      if (!term) return
      
      // Remove if already exists, add to front, keep max 10
      state.recentSearches = [
        term,
        ...state.recentSearches.filter(s => s.toLowerCase() !== term.toLowerCase())
      ].slice(0, 10)
      
      // Persist to localStorage
      localStorage.setItem('devhub-recent-searches', JSON.stringify(state.recentSearches))
    },
    
    // Clear all recent searches
    clearRecentSearches: (state) => {
      state.recentSearches = []
      localStorage.removeItem('devhub-recent-searches')
    },
    
    // Update filters
    setFilter: (state, action) => {
      state.filters = { ...state.filters, ...action.payload }
    },
    
    // Reset filters to default
    resetFilters: (state) => {
      state.filters = { language: '', sort: 'stars', order: 'desc' }
    },
  },
})

// Export actions (auto-generated by createSlice)
export const { 
  setQuery, 
  addRecentSearch, 
  clearRecentSearches, 
  setFilter, 
  resetFilters 
} = searchSlice.actions

// Export reducer
export default searchSlice.reducer